# MLFF Settings
potential_path:
job_type_opt: "omat"
job_type_bh: "omat"

# Model Creation Settings
metal:
oxide:
lattice_plane:
  a:
  b:
  c:
expand:
  x:
  y:
  z:
vacuum:
m_num:
o_num:
dist:

# Simulated Annealing + Basin Hopping Settings
bh_constrain_layers:
t_beg:
t_end:
hop_steps:
n_stages:
disturbance:
f_max:
step_max:

# IO Settings
cif_path:
out_path:
